name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Transfer code to Raspberry Pi
        uses: appleboy/scp-action@v1
        with:
          host: ${{secrets.RASP_DB_HOST}}
          username: ${{secrets.RASP_DB_USER}}
          password: ${{secrets.RASP_DB_PASSWORD}}
          source: .
          target: /home/hugorcd/my-project