name: Deploy to Production

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Install dependencies
        run: yarn install
      - name: Transfer code to Raspberry Pi
        uses: appleboy/scp-action@master
        with:
          host: ${{secrets.RASP_HOST}}
          username: ${{secrets.RASP_USER}}
          password: ${{secrets.RASP_PASSWORD}}
          port: ${{secrets.RASP_PORT}}
          source: .
          target: /home/${{secrets.RASP_USER}}/nuxt-app/app